inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  SupportedStyles:
    - nested
    - compact

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/rspec'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'app/channels/application_cable/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'



